FROM geoffreybooth/meteor-base:1.10.2

# Install app dependencies
RUN mkdir -p /source
WORKDIR /source
ADD package.json /source/
ADD package-lock.json /source/
RUN NODE_ENV=development meteor npm install

ENV CI_COMMIT_ID master

# Build app
ADD . /source/
ADD https://github.com/unchainedshop/unchained/archive/$CI_COMMIT_ID.tar.gz /archive.tar.gz
RUN tar -xzf /archive.tar.gz -C /
RUN cp -R /unchained-$CI_COMMIT_ID/packages /source
RUN meteor build --server-only --allow-superuser --directory /
