cd packages/@unchainedshop/types && npm version --no-git-tag-version minor &&

cd ../logger && npm version --no-git-tag-version minor &&
cd ../roles && npm version --no-git-tag-version minor &&
cd ../utils && npm version --no-git-tag-version minor &&
cd ../events && npm version --no-git-tag-version minor &&
cd ../mongodb && npm version --no-git-tag-version minor &&
cd ../file-upload && npm version --no-git-tag-version minor &&
cd ../core-worker && npm version --no-git-tag-version minor &&
cd ../core-accountsjs && npm version --no-git-tag-version minor &&
cd ../core-assortments && npm version --no-git-tag-version minor &&
cd ../core-bookmarks && npm version --no-git-tag-version minor &&
cd ../core-currencies && npm version --no-git-tag-version minor &&
cd ../core-countries && npm version --no-git-tag-version minor &&
cd ../core-delivery && npm version --no-git-tag-version minor &&
cd ../core-files && npm version --no-git-tag-version minor &&
cd ../core-languages && npm version --no-git-tag-version minor &&
cd ../core-messaging && npm version --no-git-tag-version minor &&
cd ../core-orders && npm version --no-git-tag-version minor &&
cd ../core-payment && npm version --no-git-tag-version minor &&
cd ../core-products && npm version --no-git-tag-version minor &&
cd ../core-filters && npm version --no-git-tag-version minor &&
cd ../core-users && npm version --no-git-tag-version minor &&
cd ../core-quotations && npm version --no-git-tag-version minor &&
cd ../core-enrollments && npm version --no-git-tag-version minor &&
cd ../core-warehousing && npm version --no-git-tag-version minor &&
cd ../core-events && npm version --no-git-tag-version minor &&
cd ../core && npm version --no-git-tag-version minor &&
cd .. &&
cd ../api && npm version --no-git-tag-version minor &&
cd ../platform && npm version --no-git-tag-version minor &&
cd ../../examples/minimal && npm version --no-git-tag-version minor &&
cd ../controlpanel && npm version --no-git-tag-version minor &&
cd ../../ && npm version --no-git-tag-version minor &&
