export {
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightEndOnRectangleIcon,
  BanknotesIcon,
  CalculatorIcon,
  CalendarIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClockIcon,
  Cog6ToothIcon,
  CommandLineIcon,
  CreditCardIcon,
  EllipsisHorizontalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  EyeIcon,
  FolderIcon,
  GlobeAltIcon,
  InboxIcon,
  InformationCircleIcon,
  LinkIcon,
  ListBulletIcon,
  LockClosedIcon,
  MoonIcon,
  NoSymbolIcon,
  PaperAirplaneIcon,
  PencilIcon,
  PhotoIcon,
  PlusIcon,
  QuestionMarkCircleIcon,
  RectangleStackIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SparklesIcon,
  Squares2X2Icon,
  SunIcon,
  TrashIcon,
  UserCircleIcon,
  VariableIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';

export {
  ChevronDownIcon as ChevronDownSolidIcon,
  ChevronUpIcon as ChevronUpSolidIcon,
  PencilIcon as PencilSolidIcon,
  PencilSquareIcon,
  TrashIcon as TrashSolidIcon,
} from '@heroicons/react/20/solid';

export {
  CheckCircleIcon as CheckCircleSolidIcon,
  ChevronDownIcon as ChevronDownSolid24Icon,
  StarIcon,
  XCircleIcon as XCircleSolidIcon,
} from '@heroicons/react/24/solid';
