import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    ui: 'src/components/ui/index.ts',
    form: 'src/components/ui/form/index.ts',
    hooks: 'src/sdk/hooks.ts',
    providers: 'src/sdk/providers.ts',
    modal: 'src/sdk/modal.ts',
    theme: 'src/sdk/theme.ts',
    plugins: 'src/sdk/plugins.ts',
    'shims/react': 'src/sdk/shims/react.ts',
    'shims/react-jsx-runtime': 'src/sdk/shims/react-jsx-runtime.ts',
    'shims/react-dom': 'src/sdk/shims/react-dom.ts',
    'shims/react-dom-client': 'src/sdk/shims/react-dom-client.ts',
    'shims/apollo-client': 'src/sdk/shims/apollo-client.ts',
    'shims/apollo-client-react': 'src/sdk/shims/apollo-client-react.ts',
    'shims/next-router': 'src/sdk/shims/next-router.ts',
    'shims/next-link': 'src/sdk/shims/next-link.ts',
    'shims/next-image': 'src/sdk/shims/next-image.ts',
    'shims/next-head': 'src/sdk/shims/next-head.ts',
    'shims/react-intl': 'src/sdk/shims/react-intl.ts',
    'shims/react-toastify': 'src/sdk/shims/react-toastify.ts',
    'shims/formik': 'src/sdk/shims/formik.ts',
    'shims/admin-ui-plugins': 'src/sdk/shims/admin-ui-plugins.ts',
    'modules/accounts': 'src/modules/accounts/index.ts',
    'modules/assortment': 'src/modules/assortment/index.ts',
    'modules/country': 'src/modules/country/index.ts',
    'modules/currency': 'src/modules/currency/index.ts',
    'modules/delivery-provider': 'src/modules/delivery-provider/index.ts',
    'modules/enrollment': 'src/modules/enrollment/index.ts',
    'modules/event': 'src/modules/event/index.ts',
    'modules/filter': 'src/modules/filter/index.ts',
    'modules/language': 'src/modules/language/index.ts',
    'modules/order': 'src/modules/order/index.ts',
    'modules/payment-providers': 'src/modules/payment-providers/index.ts',
    'modules/product': 'src/modules/product/index.ts',
    'modules/product-review': 'src/modules/product-review/index.ts',
    'modules/quotation': 'src/modules/quotation/index.ts',
    'modules/token': 'src/modules/token/index.ts',
    'modules/warehousing-providers':
      'src/modules/warehousing-providers/index.ts',
    'modules/work': 'src/modules/work/index.ts',
  },
  format: ['esm'],
  platform: 'browser',
  dts: false,
  splitting: true,
  treeshake: true,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'next',
    'next/link',
    'next/image',
    'next/router',
    'react-hook-form',
    '@apollo/client',
    '@apollo/client/react',
    'react-intl',
    'react-toastify',
    'graphql',
  ],
  esbuildOptions(options) {
    options.alias = {
      '@/*': './src/*',
    };
  },
});
