export const logs = [
  {
    _id: 'jtDQ89fP2MesdcsYB',
    created: 1590676199012,
    level: 'error',
    message:
      'Fields "logs" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional. GRAPHQL_VALIDATION_FAILED',
    user: null,
    order: null,
  },
  {
    _id: 'C4eyeLAAHPp6CCF7X',
    created: 1590676138647,
    level: 'info',
    message: 'query user undefined',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'reTGsaon6nbZx7Tgd',
    created: 1590675813721,
    level: 'info',
    message: 'query user undefined',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'gJthNnRsvtLrh6rdT',
    created: 1590674402241,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 17:59:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: '26yLNnaytyQi72X5b',
    created: 1590674342985,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 17:00:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'o6vcNwXHchZjvFoTN',
    created: 1590673938902,
    level: 'error',
    message: 'The user "" has no permission to perform the action "viewLogs" NoPermissionError',
    user: null,
    order: null,
  },
  {
    _id: 'RjPEwuZhrd4RbhGui',
    created: 1590673505670,
    level: 'info',
    message: 'query shopInfo',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'kPG5xbSw6euue27qo',
    created: 1590673505646,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'Wtp4enPLCJaXSvy52',
    created: 1590673504561,
    level: 'info',
    message: 'query shopInfo',
    user: null,
    order: null,
  },
  {
    _id: '4SMJo3LCeLr63cgpZ',
    created: 1590673504552,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'YbHebpT9GcihNC6Pi',
    created: 1590673504542,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'QxL8CLGfJ7WXk4rPy',
    created: 1590673482836,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 16:59:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'Rd35ePfwvBKs4KQAY',
    created: 1590673479219,
    level: 'info',
    message: 'query shopInfo',
    user: null,
    order: null,
  },
  {
    _id: 'HzHyXrC28yWkJLQJr',
    created: 1590673479213,
    level: 'info',
    message: 'query shopInfo',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'H6k45x4EXMG5C9R7K',
    created: 1590673479195,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'kDLP5bhtFCGGqGovB',
    created: 1590673479193,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: '8GZXeL22AYPz3pxw5',
    created: 1590673479191,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'obCtwTXzveq93Dnb6',
    created: 1590673478485,
    level: 'info',
    message: 'shop.unchained.worker.cron -> Initialized: bionic:CRON',
    user: null,
    order: null,
  },
  {
    _id: 'y9rF3ryZwbNBgZZvs',
    created: 1590673478484,
    level: 'info',
    message: 'shop.unchained.worker.event-listener -> Initialized: bionic:EVENT_LISTENER',
    user: null,
    order: null,
  },
  {
    _id: 'xc2KbESXLyR6fygHa',
    created: 1590673478483,
    level: 'info',
    message:
      'WorkerDirector -> Configured ENROLLMENT_ORDER_GENERATOR shop.unchained.worker-plugin.generate-enrollment-orders@1.0 (Generates new Orders from Enrollments) for Autorun at every 59 minutes',
    user: null,
    order: null,
  },
  {
    _id: 'bYirkXrhF5f9Cha9M',
    created: 1590673478099,
    level: 'info',
    message:
      'WorkerDirector -> Registered MESSAGE shop.unchained.worker-plugin.message@1.0 (Send Message by combining payload with a template and start concrete jobs)',
    user: null,
    order: null,
  },
  {
    _id: 'sbtdGZMcXo8ukeTfw',
    created: 1590673477769,
    level: 'info',
    message:
      'WorkerDirector -> Registered EMAIL shop.unchained.worker-plugin.email@1.0 (Send a Mail through Meteor Mailer)',
    user: null,
    order: null,
  },
  {
    _id: 'gCfnkJEMfkSuyrPnj',
    created: 1590673477768,
    level: 'info',
    message:
      'WorkerDirector -> Registered HEARTBEAT shop.unchained.worker-plugin.heartbeat@1.0 (Heartbeat plugin to check if workers are working)',
    user: null,
    order: null,
  },
  {
    _id: 'ymwKh9EdGAHu5CT6g',
    created: 1590673477767,
    level: 'info',
    message:
      'WorkerDirector -> Registered HTTP_REQUEST shop.unchained.worker-plugin.http-request@1.0 (Request a resource via http request. 200 = success)',
    user: null,
    order: null,
  },
  {
    _id: '3aYW6dCaH3oXDobR2',
    created: 1590673477765,
    level: 'info',
    message:
      'EnrollmentDirector -> Registered shop.unchained.enrollments.licensed 1.0 (Simple Licensed Enrollments)',
    user: null,
    order: null,
  },
  {
    _id: 'HbJtA8K5xBqfJTLgq',
    created: 1590673477764,
    level: 'info',
    message: 'QuotationDirector -> Registered shop.unchained.quotations.manual 1.0 (Manual Offerings)',
    user: null,
    order: null,
  },
  {
    _id: 'ZyR6ZfoZBEYex9wou',
    created: 1590673477762,
    level: 'info',
    message:
      'FilterDirector -> Registered shop.unchained.filters.local-search 0.1 (Simple Fulltext search with MongoDB)',
    user: null,
    order: null,
  },
  {
    _id: 'yHPQjLvmbTG3opvaM',
    created: 1590673477760,
    level: 'info',
    message:
      'FilterDirector -> Registered shop.unchained.filters.strict-qual 0.1 (Simple Strict Equal DB Filter)',
    user: null,
    order: null,
  },
  {
    _id: 'oPoffN5zjzDZpsXe9',
    created: 1590673477758,
    level: 'info',
    message:
      'ProductPricingDirector -> Registered shop.unchained.pricing.product-swiss-tax 1.0 (Berechnung der Bestellposition: Nettopreis und MwSt (Schweiz))',
    user: null,
    order: null,
  },
  {
    _id: 'aWBQzp3hFdnAcLMYQ',
    created: 1590673477756,
    level: 'info',
    message:
      'ProductPricingDirector -> Registered shop.unchained.pricing.product-discount 1.0 (Berechnung der Bestellposition: Prozentual-Gutscheine)',
    user: null,
    order: null,
  },
  {
    _id: 'b7Dr89bxvSPJzj3BB',
    created: 1590673477755,
    level: 'info',
    message:
      'ProductPricingDirector -> Registered shop.unchained.pricing.product-price 1.0 (Berechnung der Bestellposition: Bruttopreis)',
    user: null,
    order: null,
  },
  {
    _id: 'hfE6Ev4DQHxxHQKu4',
    created: 1590673477753,
    level: 'info',
    message:
      'OrderPricingDirector -> Registered shop.unchained.pricing.order-payment 1.0 (Bruttopreis + MwSt. aller Zahlungsgebühren summieren)',
    user: null,
    order: null,
  },
  {
    _id: 'MFhEpRC7Tyojb4r6e',
    created: 1590673477752,
    level: 'info',
    message:
      'OrderPricingDirector -> Registered shop.unchained.pricing.order-delivery 1.0 (Bruttopreis + MwSt. aller Versandgebühren summieren)',
    user: null,
    order: null,
  },
  {
    _id: '8np3DNPwCoywbW8yx',
    created: 1590673477751,
    level: 'info',
    message:
      'OrderPricingDirector -> Registered shop.unchained.pricing.order-discount 1.0 (Bruttopreis + MwSt. aller Pauschal-Gutscheine summieren)',
    user: null,
    order: null,
  },
  {
    _id: 'bT5FFE4eKcyzk49w5',
    created: 1590673477749,
    level: 'info',
    message:
      'OrderPricingDirector -> Registered shop.unchained.pricing.order-items 1.0 (Bruttopreis + MwSt. aller Artikel summieren)',
    user: null,
    order: null,
  },
  {
    _id: 'q3AwoaTENW7PAw6bc',
    created: 1590673477747,
    level: 'info',
    message: 'PaymentDirector -> Registered shop.unchained.apple-iap 1.0 (Apple In-App-Purchase)',
    user: null,
    order: null,
  },
  {
    _id: 'pAZg9LWPfYgYWF7n3',
    created: 1590673477746,
    level: 'info',
    message: 'PaymentDirector -> Registered shop.unchained.datatrans 1.0 (Datatrans)',
    user: null,
    order: null,
  },
  {
    _id: '7mBSuoPq6n7bFEX9C',
    created: 1590673477744,
    level: 'info',
    message:
      'PaymentDirector -> Registered shop.unchained.invoice-prepaid 1.0 (Invoice Prepaid (manually))',
    user: null,
    order: null,
  },
  {
    _id: 'wEggWiaiRPwxmdCsv',
    created: 1590673477742,
    level: 'info',
    message: 'PaymentDirector -> Registered shop.unchained.invoice 1.0 (Invoice (manually))',
    user: null,
    order: null,
  },
  {
    _id: '2g3uf9MHrhM9XJmSM',
    created: 1590673477741,
    level: 'info',
    message: 'DocumentDirector -> Registered shop.unchained.smallinvoice 1.0 (Smallinvoice)',
    user: null,
    order: null,
  },
  {
    _id: 'aSva6s4mj7gQvJ5wd',
    created: 1590673477740,
    level: 'info',
    message: 'DiscountDirector -> Registered shop.unchained.discount.100-off 1.0 (100 Off)',
    user: null,
    order: null,
  },
  {
    _id: '5WvxjqfQZpxqjD7wb',
    created: 1590673477738,
    level: 'info',
    message: 'DiscountDirector -> Registered shop.unchained.discount.half-price-manual 1.0 (Half Price)',
    user: null,
    order: null,
  },
  {
    _id: 'tnnzREWjpxKoArRmx',
    created: 1590673477737,
    level: 'info',
    message: 'WarehousingDirector -> Registered shop.unchained.warehousing.store 1.0 (Stores)',
    user: null,
    order: null,
  },
  {
    _id: '5QwABQmvioTd5gJjP',
    created: 1590673477736,
    level: 'info',
    message: 'DeliveryDirector -> Registered shop.unchained.stores 1.0 (Manual Pickup)',
    user: null,
    order: null,
  },
  {
    _id: 'epiq9Mxn6RPbzSAXC',
    created: 1590673477734,
    level: 'info',
    message:
      'DeliveryDirector -> Registered shop.unchained.delivery.send-message 1.0 (Forward Delivery via Messaging)',
    user: null,
    order: null,
  },
  {
    _id: '9djXAp2zmbEHRQNG2',
    created: 1590673477732,
    level: 'info',
    message: 'DeliveryDirector -> Registered shop.unchained.pick-mup 1.0 (Migros Pick M Up)',
    user: null,
    order: null,
  },
  {
    _id: 'L6TfdA7qyv6gcEoAE',
    created: 1590673477730,
    level: 'info',
    message: 'DeliveryDirector -> Registered shop.unchained.post 1.0 (Post (Manual))',
    user: null,
    order: null,
  },
  {
    _id: 'e6AAcz8TNdbPap5S4',
    created: 1590673468149,
    level: 'info',
    message:
      'WorkerDirector -> Registered ENROLLMENT_ORDER_GENERATOR shop.unchained.worker-plugin.generate-enrollment-orders@1.0 (Generates new Orders from Enrollments)',
    user: null,
    order: null,
  },
  {
    _id: 'mA4zfCLCvhmZ7Kyea',
    created: 1590673467534,
    level: 'info',
    message:
      'WorkerDirector -> Registered EXTERNAL shop.unchained.worker-plugin.external@1.0 (External plugin as a placeholder for workers who interact with the system only via GraphQL)',
    user: null,
    order: null,
  },
  {
    _id: 'HtafK2mvKR3ezXrmd',
    created: 1590620402825,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 02:59:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'nyDBkztbtzK7wKnuw',
    created: 1590620342497,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 02:00:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'vCFznjFwckt5reuFg',
    created: 1590616802039,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 01:59:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'aQoigShEDb6XQ56xY',
    created: 1590616742710,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 01:00:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'mGfwmMmzGniESQrbq',
    created: 1590613287349,
    level: 'info',
    message: 'query payment-interfaces GENERIC',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'fvxYrThpvDZfmb9Xc',
    created: 1590613275644,
    level: 'info',
    message: 'query payment-interfaces CARD',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'HETSaqSc9Spzg8aN8',
    created: 1590613261974,
    level: 'info',
    message: 'query payment-interfaces INVOICE',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'eYNM9RXxcFfFwwzif',
    created: 1590613202285,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 00:59:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: '9cCNJrosg298hkDS7',
    created: 1590613142017,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Thu May 28 2020 00:00:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'Agevf7YAeoovSmBgy',
    created: 1590612241378,
    level: 'info',
    message: 'query payment-providers undefined',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'vw44PAoYQW9ECxMN4',
    created: 1590612095627,
    level: 'info',
    message: 'query warehousing-interfaces PHYSICAL',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'f6Dg9ma7TTruskZzf',
    created: 1590612065086,
    level: 'info',
    message: 'query shopInfo',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: '73awPrvhyNK2ccmF5',
    created: 1590612065060,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'ou9NLbzJFtMpeK5Dh',
    created: 1590612062623,
    level: 'info',
    message: 'query shopInfo',
    user: null,
    order: null,
  },
  {
    _id: '3Yum6R7T4wp77TAYS',
    created: 1590612062613,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'pXfgLYFEwZS62geCZ',
    created: 1590612062602,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'ZXa7aSRH4bTB97HDc',
    created: 1590612050481,
    level: 'info',
    message: 'query shopInfo',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'YvquREB3fm3G8Fj5f',
    created: 1590612050456,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'C7GfjgopMYdTJEbZH',
    created: 1590612050363,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: {
      _id: 'admin',
      name: 'Raina Auer',
      username: 'admin',
    },
    order: null,
  },
  {
    _id: 'fRSXqCoyrYKZKxXSd',
    created: 1590612040033,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'Z9bf5aWDmpwd2xLSx',
    created: 1590612038232,
    level: 'info',
    message: 'query shopInfo',
    user: null,
    order: null,
  },
  {
    _id: 'bp7x89Y6rpp3sZdRh',
    created: 1590612038213,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'CwqYdRNdY8FWS25gr',
    created: 1590612036000,
    level: 'info',
    message: 'query shopInfo',
    user: null,
    order: null,
  },
  {
    _id: 'bA82ZStkYWgz9kW4f',
    created: 1590612035989,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: '6L8ASNuuPRwSHhqNY',
    created: 1590612035962,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: '8TaswZJy28GXz3sBM',
    created: 1590612035923,
    level: 'info',
    message: 'query shopInfo',
    user: null,
    order: null,
  },
  {
    _id: 'LNxP9pDWauYZRBhGx',
    created: 1590612035920,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'FYKSb3YRYs6GXR3ib',
    created: 1590612035904,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: '9eaa6AEpmCsv6npBg',
    created: 1590612015353,
    level: 'error',
    message:
      'The user "" has no permission to perform the action "viewWarehousingInterfaces" NoPermissionError',
    user: null,
    order: null,
  },
  {
    _id: 'xHxwEK3PbyhQBmtnz',
    created: 1590612015292,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'LocxbzBa5ara8hiKL',
    created: 1590612015281,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'Mz8jFsfFELcpBvvaP',
    created: 1590612015279,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'WDqBTGYtWinmpnzkD',
    created: 1590612015256,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: '8SgpkFrHTx3T4BvCP',
    created: 1590612015255,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'McfYAaYWz67QTWJga',
    created: 1590612015254,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'oFFjbvpZxu8sQjucE',
    created: 1590612015253,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'kdFzevFQbJ47Dkze9',
    created: 1590612015252,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'eAjYpp6qhi7jAsiJm',
    created: 1590612015251,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: 'xxgysbWHkWCsdshwi',
    created: 1590612015250,
    level: 'info',
    message: 'query me 127.0.0.1',
    user: null,
    order: null,
  },
  {
    _id: '5MWjGJfzMpQSHX8FA',
    created: 1590612007491,
    level: 'info',
    message:
      'WorkerDirector -> Work added ENROLLMENT_ORDER_GENERATOR Wed May 27 2020 23:59:00 GMT+0300 (East Africa Time) 0',
    user: null,
    order: null,
  },
  {
    _id: 'DFHo95MdQiS8uKF5X',
    created: 1590612006925,
    level: 'info',
    message: 'shop.unchained.worker.cron -> Initialized: bionic:CRON',
    user: null,
    order: null,
  },
  {
    _id: 'h3Ees2ceYfYeu4yHb',
    created: 1590612006924,
    level: 'info',
    message: 'shop.unchained.worker.event-listener -> Initialized: bionic:EVENT_LISTENER',
    user: null,
    order: null,
  },
  {
    _id: 'Bt6GhPpXr43EZPjEr',
    created: 1590612006923,
    level: 'info',
    message:
      'WorkerDirector -> Configured ENROLLMENT_ORDER_GENERATOR shop.unchained.worker-plugin.generate-enrollment-orders@1.0 (Generates new Orders from Enrollments) for Autorun at every 59 minutes',
    user: null,
    order: null,
  },
  {
    _id: 'tpcdWY6twodTgM9GQ',
    created: 1590612002496,
    level: 'info',
    message:
      'WorkerDirector -> Registered MESSAGE shop.unchained.worker-plugin.message@1.0 (Send Message by combining payload with a template and start concrete jobs)',
    user: null,
    order: null,
  },
  {
    _id: 'Rtx4fKyNqTYfXvuP2',
    created: 1590611921041,
    level: 'info',
    message:
      'WorkerDirector -> Registered EMAIL shop.unchained.worker-plugin.email@1.0 (Send a Mail through Meteor Mailer)',
    user: null,
    order: null,
  },
  {
    _id: 'B4NRGYGHan2tFz72N',
    created: 1590611921040,
    level: 'info',
    message:
      'WorkerDirector -> Registered HEARTBEAT shop.unchained.worker-plugin.heartbeat@1.0 (Heartbeat plugin to check if workers are working)',
    user: null,
    order: null,
  },
  {
    _id: 'cp5k5MPhGFWz6WqTW',
    created: 1590611921039,
    level: 'info',
    message:
      'WorkerDirector -> Registered HTTP_REQUEST shop.unchained.worker-plugin.http-request@1.0 (Request a resource via http request. 200 = success)',
    user: null,
    order: null,
  },
  {
    _id: '7g6KdtRJ4iQZZhHSb',
    created: 1590611921038,
    level: 'info',
    message: 'QuotationDirector -> Registered shop.unchained.quotations.manual 1.0 (Manual Offerings)',
    user: null,
    order: null,
  },
  {
    _id: 'yrte4itc5MX5Jpgee',
    created: 1590611921038,
    level: 'info',
    message:
      'EnrollmentDirector -> Registered shop.unchained.enrollments.licensed 1.0 (Simple Licensed Enrollments)',
    user: null,
    order: null,
  },
  {
    _id: 'v2PrbX4QE8EppRsrr',
    created: 1590611921037,
    level: 'info',
    message:
      'FilterDirector -> Registered shop.unchained.filters.local-search 0.1 (Simple Fulltext search with MongoDB)',
    user: null,
    order: null,
  },
  {
    _id: 'kaqM42fgRR8FgxnP8',
    created: 1590611921036,
    level: 'info',
    message:
      'FilterDirector -> Registered shop.unchained.filters.strict-qual 0.1 (Simple Strict Equal DB Filter)',
    user: null,
    order: null,
  },
];

export default async function seedLogs(db) {
  await db.collection('logs').insertMany(logs);
}
