export const API_EVENTS = {
  API_LOGIN_TOKEN_CREATED: 'API_LOGIN_TOKEN_CREATED',
  API_LOGOUT: 'API_LOGOUT',
  ACL_DENIED: 'ACL_DENIED',
  ACL_GRANTED_SENSITIVE: 'ACL_GRANTED_SENSITIVE',
} as const;

export type API_EVENTS = (typeof API_EVENTS)[keyof typeof API_EVENTS];
